"""empty message

Revision ID: 2130e2b3edd9
Revises: c9d02cff0e66
Create Date: 2022-06-08 15:53:54.675667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2130e2b3edd9'
down_revision = 'c9d02cff0e66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'word', ['mandarin'])
    op.create_unique_constraint(None, 'word', ['phoneticM'])
    op.create_unique_constraint(None, 'word', ['phonetic'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='unique')
    op.drop_constraint(None, 'word', type_='unique')
    op.drop_constraint(None, 'word', type_='unique')
    # ### end Alembic commands ###
