"""empty message

Revision ID: 56e993cbd3ad
Revises: 2130e2b3edd9
Create Date: 2022-06-08 16:07:45.432898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e993cbd3ad'
down_revision = '2130e2b3edd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('phonetic', sa.String(length=50), nullable=False),
    sa.Column('mandarin', sa.String(length=150), nullable=False),
    sa.Column('phoneticM', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mandarin'),
    sa.UniqueConstraint('phonetic'),
    sa.UniqueConstraint('phoneticM'),
    sa.UniqueConstraint('word')
    )
    op.drop_table('word')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phonetic', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mandarin', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phoneticM', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='word_pkey'),
    sa.UniqueConstraint('mandarin', name='word_mandarin_key'),
    sa.UniqueConstraint('phonetic', name='word_phonetic_key'),
    sa.UniqueConstraint('phoneticM', name='word_phoneticM_key'),
    sa.UniqueConstraint('word', name='word_word_key')
    )
    op.drop_table('words')
    # ### end Alembic commands ###
