"""empty message

Revision ID: 5c958c593f73
Revises: c8ae03dc6491
Create Date: 2022-06-11 13:36:09.394667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c958c593f73'
down_revision = 'c8ae03dc6491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=120), nullable=False, server_default=""))
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=False, server_default=""))
    op.add_column('user', sa.Column('username', sa.String(length=120), nullable=True))
    op.drop_constraint('user_user_name_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=120), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_user_name_key', 'user', ['user_name'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
