"""empty message

Revision ID: 7a79240d83f3
Revises: 9d4542133b0c
Create Date: 2022-06-11 16:41:55.355464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a79240d83f3'
down_revision = '9d4542133b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adjacency_relation',
    sa.Column('node_id_parent', sa.Integer(), nullable=True),
    sa.Column('node_id_child', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id_child'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['node_id_parent'], ['lesson.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adjacency_relation')
    op.drop_table('lesson')
    # ### end Alembic commands ###
