"""empty message

Revision ID: c8ae03dc6491
Revises: 56e993cbd3ad
Create Date: 2022-06-10 21:34:00.428786

"""
from alembic import op
import sqlalchemy as sa
import uuid

# revision identifiers, used by Alembic.
revision = 'c8ae03dc6491'
down_revision = '56e993cbd3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=False, server_default=""))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False, server_default=""))
    op.add_column('user', sa.Column('user_name', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'user', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###
