"""empty message

Revision ID: c9d02cff0e66
Revises: b7c8a963aff1
Create Date: 2022-06-08 15:32:11.807650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d02cff0e66'
down_revision = 'b7c8a963aff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('phonetic', sa.String(length=50), nullable=False),
    sa.Column('mandarin', sa.String(length=150), nullable=False),
    sa.Column('phoneticM', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.drop_table('words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phonetic', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('mandarin', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phoneticM', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='words_pkey'),
    sa.UniqueConstraint('word', name='words_word_key')
    )
    op.drop_table('word')
    # ### end Alembic commands ###
